apiVersion: v2
name: agentbox
description: A Helm chart for deploying AgentBox - Sandbox Management Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg
keywords:
  - agentbox
  - sandbox
  - kubernetes
  - development
maintainers:
  - name: AgentBox Team
