# Default values for agentbox
# This is a YAML-formatted file.

# Image configuration
api:
  image:
    repository: ghcr.io/sciffer/agentbox
    tag: "dfbccfe"
    pullPolicy: IfNotPresent
ui:
  image:
    repository: ghcr.io/sciffer/agentbox-ui
    tag: "dfbccfe"
    pullPolicy: IfNotPresent
secrets:
  create: true
  jwtSecret: "your-jwt-secret-minimum-32-characters-long"
  adminUsername: "admin"
  adminPassword: "admin123"
  adminEmail: ""
  googleClientId: ""
  googleClientSecret: ""
  databaseDSN: ""
