# Default values for agentbox
# This is a YAML-formatted file.

# Image configuration
api:
  image:
    repository: ghcr.io/sciffer/agentbox
    tag: "main-0b2fb2b"
    pullPolicy: IfNotPresent
ui:
  image:
    repository: ghcr.io/sciffer/agentbox-ui
    tag: "main-0b2fb2b"
    pullPolicy: IfNotPresent
