{{- if .Values.rbac.create }}
{{- if .Values.rbac.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "agentbox.fullname" . }}
  labels:
    {{- include "agentbox.labels" . | nindent 4 }}
rules:
  {{- range .Values.rbac.clusterRole.rules }}
  - apiGroups: {{ .apiGroups | toYaml | nindent 4 }}
    resources: {{ .resources | toYaml | nindent 4 }}
    verbs: {{ .verbs | toYaml | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "agentbox.fullname" . }}
  labels:
    {{- include "agentbox.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "agentbox.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "agentbox.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
